-- MySQL Script generated by MySQL Workbench
-- Wed Aug 12 17:30:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sandbox
-- -----------------------------------------------------
-- 159

-- -----------------------------------------------------
-- Schema sandbox
--
-- 159
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sandbox` DEFAULT CHARACTER SET utf8 ;
USE `sandbox` ;

-- -----------------------------------------------------
-- Table `sandbox`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandbox`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_email` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sandbox`.`telegrams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandbox`.`telegrams` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `chat_id` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `telegram_user_idx` (`user_id` ASC) ,
  CONSTRAINT `telegram_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `sandbox`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sandbox`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandbox`.`publications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(254) NOT NULL,
  `text` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `publication_user_idx` (`user_id` ASC) ,
  CONSTRAINT `publication_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `sandbox`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sandbox`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandbox`.`tags` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sandbox`.`publication_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandbox`.`publication_tag` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `publication_id` BIGINT UNSIGNED NULL,
  `tag_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `publications_tags_tag_idx` (`tag_id` ASC) ,
  CONSTRAINT `publications_tags_publication`
    FOREIGN KEY (`publication_id`)
    REFERENCES `sandbox`.`publications` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `publications_tags_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `sandbox`.`tags` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
